class Sticker {
  static Map<String, List<String>> stickerCategories = {
    "Animal": [
      "images/sticker/animal/buffalo.png",
      "images/sticker/animal/crocodile.png",
      "images/sticker/animal/elephant.png",
      "images/sticker/animal/sheep.png",
    ],
    "Man": [
      "images/sticker/man/dumbbell.png",
      "images/sticker/man/listening.png",
      "images/sticker/man/play-with-pet.png",
      "images/sticker/man/tea-time.png",
    ],
    "Month": [
      "images/sticker/month/january.png",
      "images/sticker/month/february.png",
      "images/sticker/month/march.png",
      "images/sticker/month/april.png",
      "images/sticker/month/may.png",
      "images/sticker/month/june.png",
      "images/sticker/month/july.png",
      "images/sticker/month/august.png",
      "images/sticker/month/september.png",
      "images/sticker/month/october.png",
      "images/sticker/month/november.png",
      "images/sticker/month/december.png",
    ],
    "Nature": [
      "images/sticker/nature/buterflies.png",
      "images/sticker/nature/cat.png",
      "images/sticker/nature/ecology.png",
      "images/sticker/nature/flower.png",
      "images/sticker/nature/planet.png",
      "images/sticker/nature/plant-pot.png",
      "images/sticker/nature/summer.png",
      "images/sticker/nature/tulips.png",
    ],
    // "Wish": [],
    "Birthday": [
      "images/sticker/happy/birthday.png",
      "images/sticker/happy/boy.png",
      "images/sticker/happy/cake.png",
      "images/sticker/happy/confetti.png",
      "images/sticker/happy/cupcake.png",
      "images/sticker/happy/garland.png",
      "images/sticker/happy/happy-birthday.png",
      "images/sticker/happy/music.png",
      "images/sticker/happy/panda.png",
      "images/sticker/wish/balloons.png",
      "images/sticker/wish/best-wishes.png",
      "images/sticker/wish/birthday.png",
      "images/sticker/wish/star.png",
      "images/sticker/wish/make-a-wish.png",
    ],
  };
}
